# Generated by Django 4.2.2 on 2023-07-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_feedback_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='group_course',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
