# Generated by Django 4.2.2 on 2023-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_course_description_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
